language: node_js
node_js: stable
branches:
  only:
   - dev
before_install:
  - git clone https://github.com/yidreamc/yidreamc.github.io public
install:
  - npm install
script:
  - npm run build
after_success:
  - cp README.md ./public/
  - cd ./public
  - git init
  - git config --global user.name 'yidreamc'
  - git config --global user.email 'yidreamc@gmail.com'
  - git add --all
  - git commit -m "travis-ci deploy"
  - git push https://$REPO_TOKEN@github.com/yidreamc/yidreamc.github.io.git master
env:
  global:
    - GH_REF: https://github.com/yidreamc/yidreamc.github.io
