# 头部菜单，title: link
menu:
  Whoami: /about
  Github: https://github.com/yidreamc
  # Twitter: https://twitter.com/FechinLi

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
# mp3: 
  # - http://link.hhtjim.com/163/5146554.mp3
  # - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover:  /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: 'b13f1c99b04e2cb032ba'
    # 应用秘钥
    clientSecret: '8b5cec5e81b3ab9ff1b533046e66f15650d0e98c'
    # issue仓库名
    repo: 'yidreamc.github.io'
    # Github名
    owner: 'yidreamc'
    # Github名
    admin: ['yidreamc']
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: yidreamc

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-125794065-1

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
